# Generated by Django 5.0.1 on 2024-10-20 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
    ]
