# Generated by Django 5.0.1 on 2024-10-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
