# Generated by Django 5.0.4 on 2024-10-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_size_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
