# Generated by Django 5.0.4 on 2024-10-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_size_productsize_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
