# Generated by Django 5.0.4 on 2024-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products_images'),
        ),
    ]
