# Generated by Django 5.0.1 on 2024-11-15 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_product_image_product_image2_basket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='size_baskets', to='main.product'),
            preserve_default=False,
        ),
    ]
