# Generated by Django 5.0.1 on 2024-11-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_basket_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='size',
        ),
        migrations.AddField(
            model_name='basket',
            name='size_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
