# Generated by Django 5.0.1 on 2024-11-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_basket_size_basket_size_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='size_id',
        ),
    ]
