# Generated by Django 5.0.1 on 2024-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_basket_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
